---
title: "rr - proj 1"
author: "MS"
date: "6/1/2020"
output: html_document
---
## Loading and preprocessing the data
> activity <- read.csv("activity.csv", header = TRUE)

## What is mean total number of steps taken per day?
> StepsPerDay <- tapply(activity$steps, activity$date, sum)
> hist(StepsPerDay, xlab = "Number of Steps", main = "Histogram: Steps per Day")
> 

## What is the average daily activity pattern?
> MeanPerDay <- mean(StepsPerDay, na.rm = TRUE)
> MedianPerDay <- median(StepsPerDay, na.rm = TRUE)
> StepsPerInterval <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)
> plot(as.numeric(names(StepsPerInterval)), 
+      StepsPerInterval, 
+      xlab = "Interval", 
+      ylab = "Steps", 
+      main = "Average Daily Activity Pattern", 
+      type = "l")
> 
> maxInterval <- names(sort(StepsPerInterval, decreasing = TRUE)[1])
> maxSteps <- sort(StepsPerInterval, decreasing = TRUE)[1]

## Imputing missing values
> NA.vals <- sum(is.na(activity$steps))
> StepsPerInterval <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)
> # split activity data by interval
> activity.split <- split(activity, activity$interval)
> # fill in missing data for each interval
> for(i in 1:length(activity.split)){
+     activity.split[[i]]$steps[is.na(activity.split[[i]]$steps)] <- StepsPerInterval[i]
+ }
> activity.imputed <- do.call("rbind", activity.split)
> activity.imputed <- activity.imputed[order(activity.imputed$date) ,]
> StepsPerDay.imputed <- tapply(activity.imputed$steps, activity.imputed$date, sum)
> hist(StepsPerDay.imputed, xlab = "Number of Steps", main = "Histogram: Steps per Day (Imputed data)")
> MeanPerDay.imputed <- mean(StepsPerDay.imputed, na.rm = TRUE)
> MedianPerDay.imputed <- median(StepsPerDay.imputed, na.rm = TRUE)

## Are there differences in activity patterns between weekdays and weekends?
> activity.imputed$day <- ifelse(weekdays(as.Date(activity.imputed$date)) == "Saturday" | weekdays(as.Date(activity.imputed$date)) == "Sunday", "weekend", "weekday")
> # Calculate average steps per interval for weekends
> StepsPerInterval.weekend <- tapply(activity.imputed[activity.imputed$day == "weekend" ,]$steps, activity.imputed[activity.imputed$day == "weekend" ,]$interval, mean, na.rm = TRUE)
> 
> # Calculate average steps per interval for weekdays
> StepsPerInterval.weekday <- tapply(activity.imputed[activity.imputed$day == "weekday" ,]$steps, activity.imputed[activity.imputed$day == "weekday" ,]$interval, mean, na.rm = TRUE)
> 
> # Set a 2 panel plot
> par(mfrow=c(1,2))
> 
> # Plot weekday activity
> plot(as.numeric(names(StepsPerInterval.weekday)), 
+      StepsPerInterval.weekday, 
+      xlab = "Interval", 
+      ylab = "Steps", 
+      main = "Activity Pattern (Weekdays)", 
+      type = "l")
> 
> # Plot weekend activity
> plot(as.numeric(names(StepsPerInterval.weekend)), 
+      StepsPerInterval.weekend, 
+      xlab = "Interval", 
+      ylab = "Steps", 
+      main = "Activity Pattern (Weekends)", 
+      type = "l")
